spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    # sql文をコンソールとログファイルに出力する
    show-sql: true
    generate-ddl: true
logging:
  level:
    root: info
    com.zzy: debug
  # ログの出力するパスを指定
  file:
    path: log/blog.log

#開発時の環境